In [1]:
#importing the Libraies
import numpy as np
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset[['charges']]

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(indep)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
# ------------------ Decision Tree Regressor ------------------
param_grid = {
    'criterion': ['squared_error', 'absolute_error'],   # loss functions
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10]
}

grid = GridSearchCV(
    estimator=DecisionTreeRegressor(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

# fitting the model for grid search
grid.fit(X,dep)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_depth': [None, 5, 10, 20],
                         'min_samples_split': [2, 5, 10]},
             scoring='r2')

In [9]:
# Assuming 'grid' is your GridSearchCV object and has been fitted to the data
print("Best parameters:", grid.best_params_)
# Access the mean test score for the best parameters
best_index = grid.best_index_
best_r2_score = grid.cv_results_['mean_test_score'][best_index]
# Printing the best R² score
print("r2:",best_r2_score)

Best parameters: {'criterion': 'absolute_error', 'max_depth': 5, 'min_samples_split': 2}
r2: 0.8436700096396649

In [10]:
table=pd.DataFrame.from_dict(grid.cv_results_)

In [11]:
table.sort_values('rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
15,0.159257,0.049026,0.004245,0.002828,absolute_error,5,2,"{'criterion': 'absolute_error', 'max_depth': 5...",0.885227,0.781353,0.881422,0.820743,0.849605,0.843670,0.038978,1
16,0.243857,0.053204,0.009300,0.007480,absolute_error,5,5,"{'criterion': 'absolute_error', 'max_depth': 5...",0.885227,0.781353,0.881422,0.820743,0.849605,0.843670,0.038978,1
17,0.262087,0.062728,0.002897,0.000150,absolute_error,5,10,"{'criterion': 'absolute_error', 'max_depth': 5...",0.885227,0.781353,0.881422,0.820743,0.849605,0.843670,0.038978,1
5,0.015004,0.002574,0.002857,0.000085,squared_error,5,10,"{'criterion': 'squared_error', 'max_depth': 5,...",0.871005,0.779829,0.874556,0.822363,0.861384,0.841827,0.036132,4
4,0.012046,0.004935,0.008736,0.005632,squared_error,5,5,"{'criterion': 'squared_error', 'max_depth': 5,...",0.871005,0.779807,0.874556,0.822363,0.861384,0.841823,0.036139,5
3,0.012866,0.003043,0.004718,0.002012,squared_error,5,2,"{'criterion': 'squared_error', 'max_depth': 5,...",0.871181,0.779807,0.874556,0.822363,0.861057,0.841793,0.036133,6
20,0.454564,0.076402,0.016069,0.002407,absolute_error,10,10,"{'criterion': 'absolute_error', 'max_depth': 1...",0.827812,0.749391,0.832392,0.793159,0.818179,0.804187,0.030573,7
14,0.249188,0.096420,0.007373,0.006231,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_depth': N...",0.821727,0.749612,0.825741,0.793135,0.818183,0.801679,0.028416,8
23,0.181731,0.089070,0.002638,0.000284,absolute_error,20,10,"{'criterion': 'absolute_error', 'max_depth': 2...",0.821727,0.749612,0.825741,0.793135,0.818183,0.801679,0.028416,8
8,0.009985,0.003517,0.003159,0.000803,squared_error,10,10,"{'criterion': 'squared_error', 'max_depth': 10...",0.834786,0.728910,0.817145,0.779657,0.814617,0.795023,0.037581,10
11,0.009462,0.004085,0.002743,0.000040,squared_error,20,10,"{'criterion': 'squared_error', 'max_depth': 20...",0.831445,0.726459,0.812354,0.779250,0.794723,0.788846,0.035738,11
2,0.014290,0.002099,0.003698,0.001418,squared_error,None,10,"{'criterion': 'squared_error', 'max_depth': No...",0.831445,0.726459,0.812354,0.779250,0.794723,0.788846,0.035738,11
19,0.350900,0.028680,0.009138,0.007903,absolute_error,10,5,"{'criterion': 'absolute_error', 'max_depth': 1...",0.779607,0.729409,0.794357,0.776815,0.797660,0.775569,0.024453,13
7,0.008644,0.001870,0.002849,0.000156,squared_error,10,5,"{'criterion': 'squared_error', 'max_depth': 10...",0.779396,0.702334,0.803198,0.754059,0.800444,0.767886,0.037223,14
18,0.454524,0.063505,0.008441,0.005458,absolute_error,10,2,"{'criterion': 'absolute_error', 'max_depth': 1...",0.774016,0.719611,0.780798,0.767744,0.782817,0.764997,0.023307,15
13,0.341475,0.046198,0.005440,0.003148,absolute_error,None,5,"{'criterion': 'absolute_error', 'max_depth': N...",0.754507,0.656693,0.786129,0.764103,0.794539,0.751194,0.049411,16
22,0.253458,0.102528,0.005388,0.004958,absolute_error,20,5,"{'criterion': 'absolute_error', 'max_depth': 2...",0.754507,0.656693,0.786129,0.764103,0.794539,0.751194,0.049411,16
10,0.008446,0.000154,0.002935,0.000119,squared_error,20,5,"{'criterion': 'squared_error', 'max_depth': 20...",0.757309,0.695819,0.768677,0.745213,0.767426,0.746889,0.026892,18
1,0.016509,0.000956,0.006683,0.003194,squared_error,None,5,"{'criterion': 'squared_error', 'max_depth': No...",0.757309,0.695819,0.768638,0.745213,0.767426,0.746881,0.026886,19
6,0.013632,0.006899,0.005485,0.005228,squared_error,10,2,"{'criterion': 'squared_error', 'max_depth': 10...",0.766964,0.673109,0.767733,0.718142,0.771707,0.739531,0.038607,20
21,0.340651,0.057536,0.009198,0.005736,absolute_error,20,2,"{'criterion': 'absolute_error', 'max_depth': 2...",0.751794,0.589107,0.715720,0.728531,0.766320,0.710294,0.063102,21
0,0.018783,0.004975,0.008671,0.004545,squared_error,None,2,"{'criterion': 'squared_error', 'max_depth': No...",0.735914,0.646517,0.731020,0.748060,0.688427,0.709988,0.037570,22
12,0.223195,0.049409,0.003610,0.001562,absolute_error,None,2,"{'criterion': 'absolute_error', 'max_depth': N...",0.752414,0.584181,0.715721,0.728531,0.748261,0.705821,0.062261,23
9,0.020151,0.007466,0.007812,0.006232,squared_error,20,2,"{'criterion': 'squared_error', 'max_depth': 20...",0.735894,0.652098,0.719619,0.748060,0.672204,0.705575,0.037134,24

In [12]:
# Assuming 'grid' is your GridSearchCV object that has been fitted to the data
best_model = grid.best_estimator_

In [13]:
import pickle
filename="RF_G.sav"
pickle.dump(best_model,open(filename,'wb'))